# Generated by Django 4.1.6 on 2023-02-10 05:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("twitter", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("nickname", models.CharField(max_length=255)),
                ("league", models.CharField(blank=True, max_length=255, null=True)),
                ("division", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "championships",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=4),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "playoffs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=4),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("tab_id", models.CharField(blank=True, max_length=255, null=True)),
                ("cap_space", models.IntegerField(blank=True, null=True)),
                ("reserves", models.IntegerField(blank=True, null=True)),
                ("ifa_pool_space", models.IntegerField(blank=True, null=True)),
                ("roster_85_man", models.IntegerField(blank=True, null=True)),
                ("roster_40_man", models.IntegerField(blank=True, null=True)),
                ("roster_30_man", models.IntegerField(blank=True, null=True)),
                (
                    "owners",
                    models.ManyToManyField(blank=True, null=True, to="npl.owner"),
                ),
            ],
            options={
                "ordering": ["league", "division", "name"],
            },
        ),
    ]
