# Generated by Django 4.1.6 on 2023-02-10 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("birthdate_qa", models.BooleanField(default=False)),
                ("raw_age", models.IntegerField(blank=True, default=None, null=True)),
                ("mlb_org", models.CharField(blank=True, max_length=255, null=True)),
                ("mlb_id", models.CharField(max_length=255)),
                (
                    "scoresheet_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fg_id", models.CharField(blank=True, max_length=255, null=True)),
                ("bp_id", models.CharField(blank=True, max_length=255, null=True)),
                ("bref_id", models.CharField(blank=True, max_length=255, null=True)),
                ("mls_time", models.CharField(blank=True, max_length=255, null=True)),
                ("options", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("mls_year", models.CharField(blank=True, max_length=255, null=True)),
                ("is_owned", models.BooleanField(default=False)),
                ("is_roster_40_man", models.BooleanField(default=False)),
                ("is_roster_30_man", models.BooleanField(default=False)),
                ("is_roster_7_day_il", models.BooleanField(default=False)),
                ("is_roster_56_day_il", models.BooleanField(default=False)),
                ("is_roster_covid_il", models.BooleanField(default=False)),
                ("is_roster_eos_il", models.BooleanField(default=False)),
                ("is_roster_restricted", models.BooleanField(default=False)),
                ("is_roster_aaa_option", models.BooleanField(default=False)),
                ("is_roster_aaa_outright", models.BooleanField(default=False)),
                ("is_roster_aaa_foreign", models.BooleanField(default=False)),
                ("is_roster_aaa_retired", models.BooleanField(default=False)),
                ("is_roster_aaa_nri", models.BooleanField(default=False)),
                ("is_roster_aa", models.BooleanField(default=False)),
                ("is_roster_a", models.BooleanField(default=False)),
                ("stats", models.JSONField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="npl.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
