# Generated by Django 4.1.6 on 2023-02-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0002_player"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["nickname"]},
        ),
        migrations.RemoveField(
            model_name="player",
            name="id",
        ),
        migrations.AddField(
            model_name="player",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="mlb_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
