# Generated by Django 4.1.6 on 2023-02-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0003_alter_team_options_remove_player_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="raw_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
