# Generated by Django 4.1.6 on 2023-02-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0004_player_raw_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["team__name", "-is_roster_40_man", "position", "last_name"]
            },
        ),
        migrations.CreateModel(
            name="ContractYear",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("year", models.IntegerField()),
                ("amount", models.IntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="npl.player"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
