# Generated by Django 4.1.6 on 2023-02-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0006_remove_contractyear_player_contract_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"ordering": ["-total_years", "-total_amount"]},
        ),
        migrations.AddField(
            model_name="player",
            name="defense_rathing",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
