# Generated by Django 4.1.6 on 2023-02-11 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0007_alter_contract_options_player_defense_rathing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="defense_rathing",
            new_name="defense_rating",
        ),
    ]
