# Generated by Django 4.1.6 on 2023-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0008_rename_defense_rathing_player_defense_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="defense_rating",
            new_name="scoresheet_defense",
        ),
        migrations.AddField(
            model_name="player",
            name="scoresheet_offense",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
