# Generated by Django 4.1.6 on 2023-02-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0009_rename_defense_rating_player_scoresheet_defense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="bats",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="height",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="throws",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="weight",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
