# Generated by Django 4.1.6 on 2023-02-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0011_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
