# Generated by Django 4.1.6 on 2023-02-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0012_player_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="simple_position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
