# Generated by Django 4.1.6 on 2023-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0015_transaction_raw_acquiring_team_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="is_mlb_transaction",
            new_name="is_archive_transaction",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="is_npl_transaction",
        ),
        migrations.AddField(
            model_name="transaction",
            name="cash_considerations",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="raw_draft_pick",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
