# Generated by Django 4.1.6 on 2023-02-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "npl",
            "0016_rename_is_mlb_transaction_transaction_is_archive_transaction_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="raw_transaction_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
