# Generated by Django 4.1.6 on 2023-02-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0017_transaction_raw_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="npl.player",
            ),
        ),
    ]
