# Generated by Django 4.1.7 on 2023-02-26 19:50

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0018_alter_transaction_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                ("body", django_quill.fields.QuillField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date", "transaction_type__transaction_type"]},
        ),
        migrations.AlterModelOptions(
            name="transactiontype",
            options={"ordering": ["transaction_type"]},
        ),
    ]
