# Generated by Django 4.1.7 on 2023-02-26 20:12

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0019_page_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="summary",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
