# Generated by Django 4.1.7 on 2023-02-27 10:22

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0022_alter_collection_options_alter_page_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["-name"]},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("body", django_quill.fields.QuillField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="npl.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
