# Generated by Django 4.1.7 on 2023-03-11 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0024_auction_auctionbid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AuctionBid",
            new_name="NonMLBAuctionBid",
        ),
        migrations.AddField(
            model_name="auction",
            name="is_mlb_auction",
            field=models.BooleanField(
                default=True,
                help_text="Mark true for MLB auctions, which should use MLBAuctionBid. Mark false for non-MLB auctions, which should use NonMLBAuctionBid.",
            ),
        ),
        migrations.CreateModel(
            name="MLBAuctionBid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("max_bid", models.IntegerField()),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="npl.auction"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="npl.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "auction")},
            },
        ),
    ]
