# Generated by Django 4.1.7 on 2023-06-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0025_rename_auctionbid_nonmlbauctionbid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="roster_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
