# Generated by Django 4.1.7 on 2023-07-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0026_player_roster_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_mlb_eligible",
            field=models.BooleanField(default=False),
        ),
    ]
