# Generated by Django 4.1.7 on 2023-08-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0027_player_is_mlb_eligible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="checked",
        ),
        migrations.AddField(
            model_name="player",
            name="last_verified",
            field=models.IntegerField(default=0),
        ),
    ]
