# Generated by Django 4.1.7 on 2024-02-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0028_remove_player_checked_player_last_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="mlb_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
