# Generated by Django 4.1.7 on 2024-02-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0029_transaction_mlb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_roster_aaa",
            field=models.BooleanField(default=False),
        ),
    ]
