# Generated by Django 4.1.7 on 2024-03-01 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0030_player_is_roster_aaa"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nonmlbauctionbid",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="nonmlbauctionbid",
            name="auction",
        ),
        migrations.RemoveField(
            model_name="nonmlbauctionbid",
            name="team",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="is_mlb_auction",
        ),
        migrations.AddField(
            model_name="auction",
            name="leading_bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="leading_bid_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="npl.team",
            ),
        ),
        migrations.DeleteModel(
            name="MLBAuctionBid",
        ),
        migrations.DeleteModel(
            name="NonMLBAuctionBid",
        ),
    ]
