# Generated by Django 4.1.7 on 2024-03-01 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0031_alter_nonmlbauctionbid_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="leading_bid",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="leading_bid_team",
        ),
        migrations.CreateModel(
            name="MLBAuctionBid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("max_bid", models.IntegerField()),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="npl.auction"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="npl.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "auction")},
            },
        ),
    ]
