# Generated by Django 4.1.7 on 2025-01-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0032_remove_auction_leading_bid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("year", models.IntegerField()),
                ("year_start", models.DateField(blank=True, null=True)),
                ("year_end", models.DateField(blank=True, null=True)),
                ("term_pay_1", models.DateField(blank=True, null=True)),
                ("term_pay_2", models.DateField(blank=True, null=True)),
                ("opening_day", models.DateField(blank=True, null=True)),
                ("league_min", models.IntegerField(blank=True, null=True)),
                ("qo_salary", models.IntegerField(blank=True, null=True)),
                ("salary_cap", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": [
                    "team__short_name",
                    "-roster_40man",
                    "position",
                    "last_name",
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["full_name"]},
        ),
        migrations.RemoveField(
            model_name="owner",
            name="first_year",
        ),
        migrations.RemoveField(
            model_name="player",
            name="birthdate_qa",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_mlb_eligible",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_owned",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_30_man",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_40_man",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_56_day_il",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_7_day_il",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_a",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_aa",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_aaa",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_aaa_foreign",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_aaa_nri",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_aaa_option",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_aaa_outright",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_aaa_retired",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_covid_il",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_eos_il",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_roster_restricted",
        ),
        migrations.RemoveField(
            model_name="player",
            name="last_verified",
        ),
        migrations.RemoveField(
            model_name="team",
            name="championships",
        ),
        migrations.RemoveField(
            model_name="team",
            name="name",
        ),
        migrations.RemoveField(
            model_name="team",
            name="nickname",
        ),
        migrations.RemoveField(
            model_name="team",
            name="playoffs",
        ),
        migrations.RemoveField(
            model_name="team",
            name="roster_30_man",
        ),
        migrations.RemoveField(
            model_name="team",
            name="roster_40_man",
        ),
        migrations.RemoveField(
            model_name="team",
            name="roster_85_man",
        ),
        migrations.AddField(
            model_name="owner",
            name="discord",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="year_joined",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="year_left",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="activation_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="grad_year",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="has_been_npl40",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="has_been_outright",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="has_been_qo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="has_been_rostered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="is_r5",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="r5_return_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="r5_return_team",
                to="npl.team",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="recall_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_30man",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_40man",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_56dayIL",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_7dayIL",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_85man",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_doubleA",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_eosIL",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_foreign",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_nonroster",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_outrighted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_owaivers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_r5waivers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_restricted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_singleA",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="roster_tripleA",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="service_time",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="waiver_clear",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="abbreviation",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="double_a_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="final_season",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="full_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="initial_season",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="short_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="single_a_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="triple_a_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="options",
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.CreateModel(
            name="TeamSeason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("wins", models.IntegerField(blank=True, null=True)),
                ("losses", models.IntegerField(blank=True, null=True)),
                ("division_place", models.IntegerField(blank=True, null=True)),
                ("wild_card", models.BooleanField(default=False)),
                ("won_division", models.BooleanField(default=False)),
                ("won_wild_card", models.BooleanField(default=False)),
                ("won_divisional_series", models.BooleanField(default=False)),
                ("won_league_championship", models.BooleanField(default=False)),
                ("won_world_series", models.BooleanField(default=False)),
                ("roster_85_man", models.IntegerField(blank=True, null=True)),
                ("roster_40_man", models.IntegerField(blank=True, null=True)),
                ("roster_30_man", models.IntegerField(blank=True, null=True)),
                ("contract_salary", models.IntegerField(blank=True, null=True)),
                ("carried_salary", models.IntegerField(blank=True, null=True)),
                ("cash_borrowing", models.IntegerField(blank=True, null=True)),
                ("cap_space", models.IntegerField(blank=True, null=True)),
                ("luxury_cap_space", models.IntegerField(blank=True, null=True)),
                ("cash", models.IntegerField(blank=True, null=True)),
                ("ifa", models.IntegerField(blank=True, null=True)),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="npl.division",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="npl.league",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="npl.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="npl.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="division",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="npl.league",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="npl.division",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="npl.league",
            ),
        ),
    ]
