# Generated by Django 4.1.7 on 2025-01-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0033_division_league_season_alter_player_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="roster_tripleA_option",
            field=models.BooleanField(default=False),
        ),
    ]
