# Generated by Django 4.1.7 on 2025-01-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0034_player_roster_triplea_option"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="ifa_pool_space",
        ),
        migrations.RemoveField(
            model_name="team",
            name="reserves",
        ),
        migrations.AddField(
            model_name="team",
            name="carried_salary",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="cash",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="cash_borrowing",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="contract_salary",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="ifa",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="luxury_cap_space",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
