# Generated by Django 4.1.7 on 2025-01-26 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0034_player_npl_status"),
        ("npl", "0035_remove_team_ifa_pool_space_remove_team_reserves_and_more"),
    ]

    operations = []
