# Generated by Django 4.1.7 on 2025-01-26 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0036_merge_20250126_1721"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="fg_injury_description",
        ),
        migrations.RemoveField(
            model_name="player",
            name="fg_is_bench",
        ),
        migrations.RemoveField(
            model_name="player",
            name="fg_is_injured",
        ),
        migrations.RemoveField(
            model_name="player",
            name="fg_is_mlb40man",
        ),
        migrations.RemoveField(
            model_name="player",
            name="fg_is_starter",
        ),
        migrations.RemoveField(
            model_name="player",
            name="fg_role",
        ),
        migrations.RemoveField(
            model_name="player",
            name="fg_role_type",
        ),
    ]
