# Generated by Django 4.1.7 on 2025-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0038_player_is_owned"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="fg_role_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
