# Generated by Django 4.1.7 on 2025-01-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0040_player_fg_is_injured"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="fg_role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
