# Generated by Django 4.1.7 on 2025-01-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0041_player_fg_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="fg_injury_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="fg_is_bench",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="fg_is_mlb40man",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="fg_is_starter",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="player",
            name="fg_is_injured",
            field=models.BooleanField(default=False),
        ),
    ]
