# Generated by Django 4.1.7 on 2025-02-28 20:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0042_player_fg_injury_description_player_fg_is_bench_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftPick",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "draft_type",
                    models.CharField(
                        choices=[
                            ("aa", "aa"),
                            ("open", "open"),
                            ("balance", "balance"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("draft_round", models.IntegerField(null=True)),
                ("year", models.CharField(max_length=4)),
                ("pick_number", models.IntegerField(blank=True, null=True)),
                ("overall_pick_number", models.IntegerField(blank=True, null=True)),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("offseason", "offseason"),
                            ("midseason", "midseason"),
                        ],
                        max_length=255,
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                ("team_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "player_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pick_notes", models.TextField(blank=True, null=True)),
                ("skipped", models.BooleanField(default=False)),
                (
                    "original_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="original_team",
                        to="npl.team",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="npl.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draftpick_team",
                        to="npl.team",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-year",
                    "-season",
                    "draft_type",
                    "draft_round",
                    "pick_number",
                ],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("date", models.DateField()),
                ("season", models.IntegerField(blank=True, null=True)),
                ("trade_summary", models.TextField(blank=True, null=True)),
                ("trade_cache", models.JSONField(blank=True, null=True)),
                ("teams", models.ManyToManyField(blank=True, to="npl.team")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TradeSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("season", models.CharField(blank=True, max_length=255, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("players only", "players only"),
                            ("players and picks", "players and picks"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["-season", "trade_type"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_team",
                        to="npl.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WishlistPlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("tier", models.IntegerField(blank=True, null=True)),
                ("future_value", models.IntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "player_type",
                    models.CharField(
                        blank=True,
                        choices=[("PRO", "pro"), ("AM", "am"), ("INT", "int")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "player_school",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "player_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COL", "col"),
                            ("HS", "hs"),
                            ("MLB", "mlb"),
                            ("MINORS", "minors"),
                            ("NPB", "npb"),
                            ("KBO", "kbo"),
                            ("INT-AM", "int-am"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("player_year", models.IntegerField(blank=True, null=True)),
                ("player_fv", models.IntegerField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="npl.player"
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="npl.wishlist"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TradeReceipt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "picks",
                    models.ManyToManyField(
                        blank=True, related_name="picks", to="npl.draftpick"
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True, related_name="players", to="npl.player"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tradereceipt_team",
                        to="npl.team",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="npl.trade",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
