# Generated by Django 4.1.7 on 2025-02-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0043_draftpick_trade_tradesummary_wishlist_wishlistplayer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistplayer",
            name="player_risk",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
