# Generated by Django 4.1.7 on 2025-02-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npl", "0044_wishlistplayer_player_risk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlistplayer",
            name="future_value",
        ),
        migrations.AddField(
            model_name="wishlistplayer",
            name="interesting",
            field=models.BooleanField(default=False),
        ),
    ]
