# Generated by Django 5.2 on 2025-06-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0045_remove_wishlistplayer_future_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistplayer',
            options={'ordering': ['wishlist', 'rank', 'player']},
        ),
        migrations.AddField(
            model_name='auction',
            name='is_nomination',
            field=models.BooleanField(default=False, help_text='Nominations are non-binding; bids are required to win'),
        ),
        migrations.AddField(
            model_name='auction',
            name='min_bid',
            field=models.IntegerField(default=1, help_text='Minimum bid amount in dollars'),
        ),
        migrations.AlterField(
            model_name='mlbauctionbid',
            name='max_bid',
            field=models.IntegerField(help_text='Bid amount in dollars'),
        ),
    ]
