# Generated by Django 5.2 on 2025-06-03 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0046_alter_wishlistplayer_options_auction_is_nomination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for nomination (optional)', null=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomination_details', to='npl.auction')),
                ('nominating_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.team')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
