# Generated by Django 5.2.1 on 2025-06-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0048_transactionsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': [models.Case(models.When(level='MLB', then=1), models.When(level='AAA', then=2), models.When(level='AA', then=3), models.When(level='A', then=4), models.When(level='Rookie', then=5), models.When(level='Foreign', then=6), models.When(level='IL', then=7), models.When(level='Restricted', then=8), models.When(level='Retired', then=9), default=10, output_field=models.IntegerField()), models.Case(models.When(simple_position='P', then=1), models.When(simple_position='C', then=2), models.When(simple_position='1B', then=3), models.When(simple_position='2B', then=4), models.When(simple_position='3B', then=5), models.When(simple_position='SS', then=6), models.When(simple_position='IF', then=7), models.When(simple_position='RF', then=8), models.When(simple_position='CF', then=9), models.When(simple_position='LF', then=10), models.When(simple_position='OF', then=11), models.When(simple_position='UT', then=12), models.When(simple_position='DH', then=13), default=14, output_field=models.IntegerField()), 'last_name']},
        ),
    ]
