# Generated by Django 5.2.1 on 2025-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0049_alter_player_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_level',
            field=models.CharField(choices=[('MLB', 'MLB'), ('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('Rookie', 'Rookie'), ('Foreign', 'Foreign'), ('IL', 'Injured List'), ('Restricted', 'Restricted'), ('Retired', 'Retired'), ('Unknown', 'Unknown')], default='Unknown', help_text='Computed field for sorting', max_length=20),
        ),
    ]
