# Generated by Django 5.2.1 on 2026-10-09 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_transaction_types(apps, schema_editor):
    """Attach canonical codes to TransactionType without dropping legacy labels."""
    TransactionType = apps.get_model("npl", "TransactionType")
    from npl.transactions.catalog import KINDS

    for kind in KINDS.values():
        row = TransactionType.objects.filter(code=kind["code"]).first()
        if row is None:
            row = TransactionType.objects.filter(
                transaction_type__iexact=kind["label"], code__isnull=True
            ).first()
        if row is None:
            TransactionType.objects.create(
                transaction_type=kind["label"],
                code=kind["code"],
                category=kind["category"],
                requires_agreement=kind["requires_agreement"],
                requires_contract=kind["requires_contract"],
            )
            continue
        row.code = kind["code"]
        row.category = kind["category"]
        row.requires_agreement = kind["requires_agreement"]
        row.requires_contract = kind["requires_contract"]
        row.save()


def unseed_transaction_types(apps, schema_editor):
    TransactionType = apps.get_model("npl", "TransactionType")
    TransactionType.objects.filter(code__isnull=False).update(
        code=None,
        category=None,
        requires_agreement=False,
        requires_contract=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0050_add_level_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': [models.Case(models.When(player_level='MLB', then=1), models.When(player_level='IL', then=2), models.When(player_level='Restricted', then=3), models.When(player_level='Retired', then=4), models.When(player_level='AAA', then=5), models.When(player_level='AA', then=6), models.When(player_level='A', then=7), models.When(player_level='Rookie', then=8), models.When(player_level='Foreign', then=9), default=10, output_field=models.IntegerField()), models.Case(models.When(simple_position='P', then=1), models.When(simple_position='C', then=2), models.When(simple_position='1B', then=3), models.When(simple_position='2B', then=4), models.When(simple_position='3B', then=5), models.When(simple_position='SS', then=6), models.When(simple_position='IF', then=7), models.When(simple_position='RF', then=8), models.When(simple_position='CF', then=9), models.When(simple_position='LF', then=10), models.When(simple_position='OF', then=11), models.When(simple_position='UT', then=12), models.When(simple_position='DH', then=13), default=14, output_field=models.IntegerField()), 'last_name']},
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_kind',
            field=models.CharField(choices=[('in_season_dollars', 'In-season free agency (dollars)'), ('offseason_points', 'Offseason free agency (points)'), ('ifa_dollars', 'IFA (dollars)'), ('mlc_points', 'Minor-league contract (points)')], default='in_season_dollars', max_length=32),
        ),
        migrations.AddField(
            model_name='auction',
            name='bid_unit',
            field=models.CharField(choices=[('dollars', 'Dollars'), ('points', 'Points')], default='dollars', max_length=16),
        ),
        migrations.AddField(
            model_name='mlbauctionbid',
            name='max_bid_decimal',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minor-league contract bids, in tenths of a point (maximum 9.9).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='can_transact',
            field=models.BooleanField(default=True, help_text='Unpaid or vacant clubs are frozen and cannot submit transactions.'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='requires_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='requires_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='min_bid',
            field=models.IntegerField(default=1, help_text='Minimum bid amount in dollars or whole points'),
        ),
        migrations.AlterField(
            model_name='mlbauctionbid',
            name='max_bid',
            field=models.IntegerField(help_text='Bid amount in dollars or whole points'),
        ),
        migrations.CreateModel(
            name='DraftSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.CharField(max_length=4)),
                ('half', models.CharField(choices=[('offseason', 'Offseason'), ('midseason', 'Midseason')], default='offseason', max_length=16)),
                ('draft_type', models.CharField(choices=[('rule4', 'Rule 4'), ('rule5', 'Rule 5'), ('open', 'Open'), ('aa', 'AA'), ('balance', 'Balance')], max_length=16)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('open', 'Open'), ('complete', 'Complete')], default='scheduled', max_length=16)),
                ('selection_fee', models.IntegerField(default=0, help_text='Cash charged to the selecting club. Rule 5 is $100,000.')),
                ('current_pick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_the_clock', to='npl.draftpick')),
            ],
            options={
                'ordering': ['-year', 'draft_type'],
            },
        ),
        migrations.CreateModel(
            name='MinorLeagueOptOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('salary_june_1', models.IntegerField(blank=True, null=True)),
                ('salary_july_15', models.IntegerField(blank=True, null=True)),
                ('salary_august_15', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_outs', to='npl.player')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npl.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_outs', to='npl.team')),
            ],
            options={
                'ordering': ['team', 'player'],
            },
        ),
        migrations.CreateModel(
            name='Rule4Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('pick', models.IntegerField()),
                ('round_pick', models.IntegerField()),
                ('slot_value', models.IntegerField()),
            ],
            options={
                'ordering': ['-year', 'round', 'pick'],
                'unique_together': {('year', 'round', 'pick')},
            },
        ),
        migrations.CreateModel(
            name='TransactionProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('kind', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('awaiting_agreement', 'Awaiting agreement'), ('agreed', 'Agreed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('executed', 'Executed'), ('voided', 'Voided')], default='proposed', max_length=32)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('processing_week', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web form'), ('api', 'API'), ('mcp', 'MCP'), ('sheet', 'Sheet import')], default='web', max_length=16)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('contract_terms', models.JSONField(blank=True, null=True)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='npl.auction')),
                ('originating_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_transactions', to='npl.team')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npl.season')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_proposals', to=settings.AUTH_USER_MODEL)),
                ('transaction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npl.transactiontype')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TransactionParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('role', models.CharField(choices=[('originator', 'Originator'), ('counterparty', 'Counterparty')], max_length=20)),
                ('agreement_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='not_required', max_length=20)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('agreed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_agreements', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_parties', to='npl.team')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='npl.transactionproposal')),
            ],
            options={
                'ordering': ['proposal', 'role', 'team'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('asset_type', models.CharField(max_length=32)),
                ('mlb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scoresheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_label', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('contract_terms', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('draft_pick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npl.draftpick')),
                ('executed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_assets', to='npl.transaction')),
                ('from_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_sent', to='npl.team')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npl.player')),
                ('to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_received', to='npl.team')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='npl.transactionproposal')),
            ],
            options={
                'ordering': ['proposal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RestrictedListStint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('rl_type', models.CharField(blank=True, max_length=32, null=True)),
                ('placed_on', models.DateField(blank=True, null=True)),
                ('mlb_reinstatement', models.DateField(blank=True, null=True)),
                ('placed_back_by', models.DateField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('suspension_days', models.IntegerField(blank=True, null=True)),
                ('unpaid_portion', models.IntegerField(blank=True, null=True)),
                ('service_time_debit', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active_stint', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_stints', to='npl.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_stints', to='npl.team')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_stints', to='npl.transactionproposal')),
            ],
            options={
                'ordering': ['-placed_on', '-created'],
            },
        ),
        migrations.CreateModel(
            name='InjuredListStint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('length', models.CharField(choices=[('7', '7-day'), ('56', '56-day'), ('eos', 'End of season')], max_length=8)),
                ('placed_on', models.DateField(blank=True, null=True)),
                ('earliest_reinstatement', models.DateField(blank=True, null=True)),
                ('mlb_activation', models.DateField(blank=True, null=True)),
                ('required_activation', models.DateField(blank=True, null=True)),
                ('penalty_amount', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active_stint', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='il_stints', to='npl.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='il_stints', to='npl.team')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='il_stints', to='npl.transactionproposal')),
            ],
            options={
                'ordering': ['-placed_on', '-created'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='resulting_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_auction', to='npl.transactionproposal'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_rows', to='npl.transactionproposal'),
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('waiver_type', models.CharField(choices=[('outright', 'Outright'), ('release', 'Release'), ('trade', 'Trade'), ('rule5', 'Rule 5')], default='outright', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('cleared', 'Cleared'), ('claimed', 'Claimed'), ('returned', 'Returned'), ('withdrawn', 'Withdrawn')], default='open', max_length=16)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('mls_snapshot', models.CharField(blank=True, max_length=32, null=True)),
                ('options_remaining', models.IntegerField(blank=True, null=True)),
                ('veteran_disposition', models.CharField(blank=True, choices=[('', ''), ('keep_40', 'Keep on 40-man if cleared'), ('release', 'Release if cleared')], default='', max_length=16)),
                ('placed_on', models.DateField(blank=True, null=True)),
                ('clears_on', models.DateField(blank=True, null=True)),
                ('opens', models.DateTimeField(blank=True, null=True)),
                ('closes', models.DateTimeField(blank=True, null=True)),
                ('claiming_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waivers_claimed', to='npl.team')),
                ('placing_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers_placed', to='npl.team')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npl.player')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiver', to='npl.transactionproposal')),
            ],
            options={
                'ordering': ['-placed_on', '-created'],
            },
        ),
        migrations.CreateModel(
            name='WaiverClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_claims', to='npl.team')),
                ('waiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='npl.waiver')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('waiver', 'team')},
            },
        ),
        migrations.RunPython(seed_transaction_types, unseed_transaction_types),
    ]
