# Generated by Django 5.2.1 on 2026-10-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0051_transaction_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sta',
            field=models.CharField(blank=True, default='', help_text='Roster status flags from the sheets: QO, OR, R5, ORFA.', max_length=32),
        ),
        migrations.AddField(
            model_name='restrictedliststint',
            name='accrues_salary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restrictedliststint',
            name='accrues_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restrictedliststint',
            name='counts_against_40',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionasset',
            name='qualifier',
            field=models.CharField(blank=True, default='', help_text='Distinguishes a Rule 5 draft pick from a Rule 4 pick.', max_length=16),
        ),
        migrations.AddField(
            model_name='waiver',
            name='service_class',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='injuredliststint',
            name='length',
            field=models.CharField(choices=[('7', '7-day'), ('56', '56-day'), ('eos', 'End of season'), ('covid', 'COVID')], max_length=8),
        ),
        migrations.CreateModel(
            name='InLimboAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('placed_on', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active_assignment', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limbo_assignments', to='npl.player')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limbo', to='npl.transactionproposal')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limbo_assignments', to='npl.team')),
            ],
            options={
                'ordering': ['-placed_on', '-created'],
            },
        ),
        migrations.CreateModel(
            name='FreeAgentListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('pool', models.CharField(choices=[('mlb_current', 'Current MLB free agents'), ('milb_current', 'Current free agents with no MLB service'), ('mlb_prior', 'Earlier MLB free agents'), ('milb_prior', 'Earlier free agents with no MLB service at release')], max_length=32)),
                ('season_year', models.IntegerField()),
                ('entered_via_auction', models.BooleanField(default=False)),
                ('sta', models.CharField(blank=True, default='', max_length=32)),
                ('former_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='former_free_agents', to='npl.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_agent_listings', to='npl.player')),
            ],
            options={
                'ordering': ['-season_year', 'pool', 'player'],
                'unique_together': {('player', 'pool', 'season_year')},
            },
        ),
        migrations.CreateModel(
            name='Rule5Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('round_number', models.IntegerField()),
                ('pick_number', models.IntegerField()),
                ('outcome', models.CharField(choices=[('open', 'Open'), ('selected', 'Selected'), ('pass', 'Pass'), ('skip', 'Skip'), ('ineligible', 'Ineligible')], default='open', max_length=16)),
                ('holding_team', models.ForeignKey(blank=True, help_text='The club named in TRADED?, when the slot has been dealt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule5_held_slots', to='npl.team')),
                ('original_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule5_original_slots', to='npl.team')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npl.player')),
                ('selected_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule5_players_lost', to='npl.team')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule5_slots', to='npl.draftsession')),
            ],
            options={
                'ordering': ['session', 'round_number', 'pick_number'],
                'unique_together': {('session', 'round_number', 'pick_number')},
            },
        ),
    ]
