# Generated by Django 5.2.1 on 2026-10-10 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0052_sheet_workflow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionproposal',
            name='flag_note',
            field=models.TextField(blank=True, default='', help_text='What the club needs to fix. Shown to that club and to API clients.'),
        ),
        migrations.AddField(
            model_name='transactionproposal',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Directors mark a proposal improper when the club needs to change it.'),
        ),
        migrations.AddField(
            model_name='transactionproposal',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionproposal',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_transaction_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('token_prefix', models.CharField(max_length=16)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('scope', models.CharField(choices=[('read', 'Read'), ('read_write', 'Read and write')], max_length=16)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
