# Generated by Django 5.2.1 on 2026-10-09 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0052_sheet_workflow_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFinancialLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=32)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('counterparty', models.CharField(blank=True, default='', max_length=255)),
                ('player_name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('text_value', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('counterparty_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_financial_lines', to='npl.team')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_lines', to='npl.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_lines', to='npl.team')),
            ],
            options={
                'ordering': ['section', 'sort_order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='TeamLedgerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField()),
                ('payroll', models.IntegerField(blank=True, null=True)),
                ('cap_space', models.IntegerField(blank=True, null=True)),
                ('cash', models.IntegerField(blank=True, null=True)),
                ('luxury_tax', models.IntegerField(blank=True, null=True)),
                ('luxury_note', models.CharField(blank=True, default='', max_length=255)),
                ('salary_cap', models.IntegerField(blank=True, null=True)),
                ('available_cap', models.IntegerField(blank=True, null=True)),
                ('cash_reserves', models.IntegerField(blank=True, null=True)),
                ('roster_85', models.IntegerField(blank=True, null=True)),
                ('roster_40', models.IntegerField(blank=True, null=True)),
                ('roster_30', models.IntegerField(blank=True, null=True)),
                ('ifa_base', models.IntegerField(blank=True, null=True)),
                ('ifa_acquired', models.IntegerField(blank=True, null=True)),
                ('ifa_total', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_years', to='npl.team')),
            ],
            options={
                'ordering': ['year'],
                'constraints': [models.UniqueConstraint(fields=('team', 'year'), name='unique_team_ledger_year')],
            },
        ),
    ]
